colorScheme = "forest"
defaultBackgroundImage = "image.jpg"
defaultAppearance = "light"

[homepage]
layout = "background"
homepageImage = "1.gif"
showRecent = true
cardView = true

[header]
layout = "fixed"

[footer]
showMenu = "Fanpage"
showScrollToTop = ""
showCopyright = ""
